// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw5y85yHQE8UVdkHp7NU7Kb_hAOZVd4eI',
    appId: '1:487792309013:web:a59e9f9788084ccad0af1c',
    messagingSenderId: '487792309013',
    projectId: 'thesisapp-92868',
    authDomain: 'thesisapp-92868.firebaseapp.com',
    storageBucket: 'thesisapp-92868.firebasestorage.app',
    measurementId: 'G-Q8XDY2TNM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjimiTtH0tLWAvQ68Iwh3c35OPo8TsKrw',
    appId: '1:487792309013:android:135bb8b040f857d3d0af1c',
    messagingSenderId: '487792309013',
    projectId: 'thesisapp-92868',
    storageBucket: 'thesisapp-92868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0D2Nsc_EliO0oVGhhwcqtlKsqc49MKUk',
    appId: '1:487792309013:ios:da8e969ef07a47e0d0af1c',
    messagingSenderId: '487792309013',
    projectId: 'thesisapp-92868',
    storageBucket: 'thesisapp-92868.firebasestorage.app',
    iosBundleId: 'com.example.urinalysisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0D2Nsc_EliO0oVGhhwcqtlKsqc49MKUk',
    appId: '1:487792309013:ios:da8e969ef07a47e0d0af1c',
    messagingSenderId: '487792309013',
    projectId: 'thesisapp-92868',
    storageBucket: 'thesisapp-92868.firebasestorage.app',
    iosBundleId: 'com.example.urinalysisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw5y85yHQE8UVdkHp7NU7Kb_hAOZVd4eI',
    appId: '1:487792309013:web:19d07d730ca1cabad0af1c',
    messagingSenderId: '487792309013',
    projectId: 'thesisapp-92868',
    authDomain: 'thesisapp-92868.firebaseapp.com',
    storageBucket: 'thesisapp-92868.firebasestorage.app',
    measurementId: 'G-6KQRZHZ9B5',
  );
}
